### ISSUE TITLE
Bumping io.opentelemetry:* to last version ?

### ISSUE THREAD

**Issue by mikymigs** [grafana/grafana-opentelemetry-starter#47]
Hello,

It seems that the starter is currently (as of v1.3.2) relying on v1.25 of open telemetry but the current version is 1.30.1 --> https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-sdk/1.30.1

Are you planning on bumping these dependencies any time soon ? I really need this fix added in v1.30.0
https://github.com/open-telemetry/opentelemetry-java/pull/5697

Thanks a lot,

**Comment by zeitlinger** [comment]
You can simply bump the metrics SDK, since it's stable - I just tried it out with prometheus.

`implementation 'io.opentelemetry:opentelemetry-sdk-metrics:1.30.1'`

The starter always uses the spring boot version of otel to avoid issues with some parts of otel that are not stable yet.

**Comment by zeitlinger** [comment]
Updating all otel dependencies in this way doesn't actually work, because bumping some of the dependencies requires changes in the starter - which I've already done locally so I don't forget.

I would like to understand better what your use case is that requires all otel dependencies to be upgraded - then we can probably work something out :smile:

**Comment by mikymigs** [comment]
My use-case is simple: I like to use up to date code, especially for such libs that are still quite "young" and where each version usually brings a fair share of bug fixes and added value. I wouldn't be too picky for a few versions delay but 1.25 is almost 6 months old and there's a 6 releases gap with the latest. Now I know maintaining a lib is a lot of work, I'm not complaining, just trying to understand the constraints I must deal with.

I've actually managed to bump all the libs mentioned above and didn't face any compilation error but it's true that I most likely don't use 100% of the starter code to guaranty that there won't be any runtime issue (so far so good).

**Comment by zeitlinger** [comment]
The goal of this starter is to align the versions with what spring boot is using - Spring 3.2 will update to otel 1.30.1.

The release candidate has already been released: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2.0-RC1-Release-Notes

> didn't face any compilation errors

I'd expect that logging will no longer work, because the global otel instance is no longer automatically injected into the log appender.

**Comment by mikymigs** [comment]
Thanks for the reply and infos.
I actually don't use the logging part (yet) of otel so that probably the reason why I'm not facing obvious issues.
